package:
  name: hw-app
  version: 1.1
  
numpy:
  - ''

source:
  path: ..
  
build:
  script: build.bat                 # [ win and x86_64 ]
  script: bash build.sh             # [ linux ]
  rpaths:
    - "./output_bin/bin/"
  missing_dso_whitelist:
    - "*/libc.so.6"                 # expected on
    - "*/libstdc++.so.6"            # the target system

requirements:
  build:
    - cmake
  host:
    - zlib

outputs:
  - name: hw-package
    files:
      - "./output_bin/bin/hw.exe"   					# [ win ]
      - "./output_bin/bin/zlib.dll" 					# [ win ]
      - "./output_bin/bin/hw"       					# [ linux ]
      - "./output_bin/bin/libz.*"   					# [ linux ]
    test:
      commands:
        - if not exist "%PREFIX%/output_bin/bin/hw.exe" exit 1   	# [ win ]
        - if not exist "%PREFIX%/output_bin/bin/zlib.dll"  exit 1 	# [ win ]
        - test -x "$PREFIX/output_bin/bin/hw"				# [ linux ]

about:
  home: https://github.com/sushinskiy/hw
  summary: hw is Home Work Hello World app
