package:
  name: hw-app
  version: 1.1

source:
  path: ..
  
build:
  script: build.bat                 # [ win and x86_64 ]
  script: bash build.sh             # [ linux ]
  rpaths:
    - ./output_bin/bin/
  missing_dso_whitelist:
    - "*/libc.so.6"                 # expected on
    - "*/libstdc++.so.6"            # the target system

requirements:
  build:
    - cmake
  host:
    - zlib

outputs:
  - name: hw-package
    files:
      - ./output_bin/bin/hw.exe     # [ win ]
      - ./output_bin/bin/zlib.dll   # [ win ]
      - ./output_bin/bin/hw         # [ linux ]
      - ./output_bin/bin/libz.*     # [ linux ]

test:
  files:
    hw.exe
    zlib.dll

about:
  home: https://github.com/sushinskiy/hw
  summary: hw is Home Work Hello World app
